import {
  Document,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import { readFile } from "node:fs/promises";
import path from "node:path";
import QRCode from "qrcode";

import type {
  AgentProposalData,
  AgentProposalLanguage,
  AgentProposalProperty,
} from "@/lib/agent-proposal";

type PdfProperty =
  AgentProposalProperty & {
    qrDataUrl: string;
  };

type PdfData =
  Omit<
    AgentProposalData,
    "properties"
  > & {
    properties: PdfProperty[];
    brandLogoDataUrl: string;
  };

function dictionary(
  language:
    AgentProposalLanguage
) {
  if (language === "en") {
    return {
      propertyProposal:
        "Property Proposal",
      propertyPortfolio:
        "Property Portfolio",
      preparedFor:
        "Prepared for",
      preparedBy:
        "Prepared by",
      selectedProperties:
        "Selected Properties",
      propertyType:
        "Property Type",
      listingType:
        "Listing Type",
      gallery:
        "Property Gallery",
      photos:
        "Photos",
      interestedTitle:
        "Interested in this property?",
      interestedBody:
        "Contact the agent for more information, to arrange a viewing, or to discuss the next step.",
      phoneWhatsApp:
        "Phone / WhatsApp",
      propertyDetails:
        "Property Details",
      price: "Price",
      location: "Location",
      bedrooms: "Bedrooms",
      bathrooms: "Bathrooms",
      buildingSize:
        "Building Size",
      landSize: "Land Size",
      floors: "Floors",
      parking: "Parking",
      furnishing: "Furnishing",
      certificate: "Certificate",
      roadAccess: "Road Access",
      ownership: "Ownership",
      landType: "Land Type",
      zoning: "Zoning",
      electricity:
        "Electricity",
      water: "Water",
      facilities: "Facilities",
      nearby: "Nearby",
      description:
        "Property Description",
      viewOnline:
        "View Property Online",
      scanQr:
        "Scan the QR code to view the complete live listing on Tetamo.",
      contactAgent:
        "Contact Agent",
      listingCode:
        "Listing Code",
      generatedBy:
        "Generated by Tetamo",
      page: "Page",
    };
  }

  return {
    propertyProposal:
      "Proposal Properti",
    propertyPortfolio:
      "Portfolio Properti",
    preparedFor:
      "Dipersembahkan untuk",
    preparedBy:
      "Disiapkan oleh",
    selectedProperties:
      "Properti Pilihan",
    propertyType:
      "Jenis Properti",
    listingType:
      "Tipe Listing",
    gallery:
      "Galeri Properti",
    photos:
      "Foto",
    interestedTitle:
      "Tertarik dengan properti ini?",
    interestedBody:
      "Hubungi agen untuk informasi lebih lanjut, mengatur jadwal viewing, atau membicarakan langkah berikutnya.",
    phoneWhatsApp:
      "Telepon / WhatsApp",
    propertyDetails:
      "Detail Properti",
    price: "Harga",
    location: "Lokasi",
    bedrooms: "Kamar Tidur",
    bathrooms:
      "Kamar Mandi",
    buildingSize:
      "Luas Bangunan",
    landSize: "Luas Tanah",
    floors: "Lantai",
    parking: "Parkir",
    furnishing: "Furnishing",
    certificate:
      "Sertifikat",
    roadAccess:
      "Akses Jalan",
    ownership:
      "Kepemilikan",
    landType:
      "Jenis Tanah",
    zoning: "Zoning",
    electricity:
      "Listrik",
    water: "Air",
    facilities:
      "Fasilitas",
    nearby:
      "Sekitar Properti",
    description:
      "Deskripsi Properti",
    viewOnline:
      "Lihat Properti Online",
    scanQr:
      "Scan QR code untuk melihat listing lengkap dan terbaru di Tetamo.",
    contactAgent:
      "Hubungi Agen",
    listingCode:
      "Kode Listing",
    generatedBy:
      "Dibuat dengan Tetamo",
    page: "Halaman",
  };
}

const styles =
  StyleSheet.create({
    page: {
      backgroundColor:
        "#F8F5EE",
      color: "#1C1C1E",
      fontFamily:
        "Helvetica",
      paddingTop: 34,
      paddingBottom: 36,
      paddingHorizontal: 38,
      fontSize: 10,
    },

    coverPage: {
      backgroundColor:
        "#F8F5EE",
      color: "#1C1C1E",
      fontFamily:
        "Helvetica",
      padding: 0,
    },

    coverTop: {
      paddingTop: 36,
      paddingHorizontal: 42,
      paddingBottom: 22,
    },

    logo: {
      width: 58,
      height: 58,
      objectFit: "contain",
    },

    eyebrow: {
      marginTop: 24,
      fontSize: 9,
      letterSpacing: 1.5,
      color: "#9A772B",
      textTransform:
        "uppercase",
    },

    coverTitle: {
      marginTop: 8,
      fontSize: 30,
      lineHeight: 1.1,
      fontFamily:
        "Helvetica-Bold",
      color: "#1C1C1E",
    },

    buyerLabel: {
      marginTop: 24,
      fontSize: 9,
      color: "#77726B",
    },

    buyerName: {
      marginTop: 5,
      fontSize: 21,
      fontFamily:
        "Helvetica-Bold",
      color: "#A57A24",
    },

    buyerCompany: {
      marginTop: 4,
      fontSize: 10,
      color: "#605C56",
    },

    intro: {
      marginTop: 20,
      maxWidth: 450,
      fontSize: 10.5,
      lineHeight: 1.55,
      color: "#514E49",
    },

    coverHero: {
      width: "100%",
      height: 330,
      objectFit: "cover",
      backgroundColor:
        "#E6E0D5",
    },

    coverBottom: {
      flexDirection: "row",
      justifyContent:
        "space-between",
      alignItems: "flex-end",
      paddingHorizontal: 42,
      paddingVertical: 28,
    },

    coverAgentName: {
      fontSize: 14,
      fontFamily:
        "Helvetica-Bold",
    },

    coverAgentMeta: {
      marginTop: 3,
      fontSize: 9,
      color: "#6D6963",
    },

    propertyCount: {
      fontSize: 9,
      color: "#77726B",
      textAlign: "right",
    },

    header: {
      flexDirection: "row",
      justifyContent:
        "space-between",
      alignItems: "center",
      marginBottom: 18,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor:
        "#DED8CC",
    },

    headerBrand: {
      flexDirection: "row",
      alignItems: "center",
    },

    headerLogo: {
      width: 31,
      height: 31,
      objectFit: "contain",
      marginRight: 9,
    },

    headerBrandText: {
      fontSize: 13,
      fontFamily:
        "Helvetica-Bold",
    },

    listingCode: {
      fontSize: 8.5,
      color: "#807B74",
    },

    propertyHero: {
      width: "100%",
      height: 238,
      objectFit: "cover",
      backgroundColor:
        "#E6E0D5",
      borderRadius: 5,
    },

    propertyTitle: {
      marginTop: 18,
      fontSize: 21,
      lineHeight: 1.2,
      fontFamily:
        "Helvetica-Bold",
    },

    location: {
      marginTop: 5,
      fontSize: 9.5,
      color: "#6E6962",
    },

    price: {
      marginTop: 10,
      fontSize: 17,
      fontFamily:
        "Helvetica-Bold",
      color: "#9A772B",
    },

    statGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 16,
      marginHorizontal: -4,
    },

    stat: {
      width: "25%",
      paddingHorizontal: 4,
      marginBottom: 8,
    },

    statInner: {
      minHeight: 48,
      backgroundColor:
        "#FFFFFF",
      borderWidth: 1,
      borderColor:
        "#E5E0D7",
      borderRadius: 5,
      padding: 8,
    },

    statLabel: {
      fontSize: 7.5,
      color: "#817B74",
    },

    statValue: {
      marginTop: 3,
      fontSize: 10,
      fontFamily:
        "Helvetica-Bold",
    },

    twoColumn: {
      flexDirection: "row",
      marginTop: 16,
      gap: 18,
    },

    mainColumn: {
      width: "64%",
    },

    sideColumn: {
      width: "36%",
    },

    sectionTitle: {
      fontSize: 10,
      fontFamily:
        "Helvetica-Bold",
      marginBottom: 7,
      color: "#282725",
    },

    body: {
      fontSize: 9,
      lineHeight: 1.5,
      color: "#514E49",
    },

    bullet: {
      fontSize: 8.5,
      lineHeight: 1.5,
      color: "#514E49",
      marginBottom: 2,
    },

    infoBox: {
      backgroundColor:
        "#FFFFFF",
      borderWidth: 1,
      borderColor:
        "#E5E0D7",
      borderRadius: 6,
      padding: 11,
      marginBottom: 10,
    },

    qrRow: {
      flexDirection: "row",
      alignItems: "center",
    },

    qr: {
      width: 72,
      height: 72,
      marginRight: 10,
    },

    qrCopy: {
      flex: 1,
    },

    qrTitle: {
      fontSize: 9,
      fontFamily:
        "Helvetica-Bold",
    },

    qrText: {
      marginTop: 4,
      fontSize: 7.5,
      lineHeight: 1.4,
      color: "#716C65",
    },

    coverPageNumber: {
      position: "absolute",
      bottom: 14,
      right: 20,
      backgroundColor:
        "#2A2927",
      color: "#FFFFFF",
      borderRadius: 10,
      paddingHorizontal: 9,
      paddingVertical: 4,
      fontSize: 7,
    },

    propertyKicker: {
      marginTop: 2,
      fontSize: 8,
      fontFamily:
        "Helvetica-Bold",
      letterSpacing: 1.2,
      color: "#A57A24",
      textTransform:
        "uppercase",
    },

    galleryPage: {
      backgroundColor:
        "#FFFFFF",
      color: "#1C1C1E",
      fontFamily:
        "Helvetica",
      paddingTop: 36,
      paddingBottom: 40,
      paddingHorizontal: 38,
      fontSize: 10,
    },

    galleryHeader: {
      flexDirection: "row",
      justifyContent:
        "space-between",
      alignItems: "flex-end",
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor:
        "#DED8CC",
    },

    galleryEyebrow: {
      fontSize: 7.5,
      fontFamily:
        "Helvetica-Bold",
      color: "#A57A24",
      letterSpacing: 1.1,
      textTransform:
        "uppercase",
    },

    galleryTitle: {
      marginTop: 5,
      fontSize: 20,
      fontFamily:
        "Helvetica-Bold",
      color: "#1C1C1E",
    },

    galleryPropertyTitle: {
      marginTop: 4,
      maxWidth: 390,
      fontSize: 8,
      color: "#77726B",
    },

    galleryPhotoLabel: {
      fontSize: 7,
      color: "#99938A",
      textAlign: "right",
      textTransform:
        "uppercase",
    },

    galleryPhotoRange: {
      marginTop: 4,
      fontSize: 10,
      fontFamily:
        "Helvetica-Bold",
      textAlign: "right",
    },

    galleryGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent:
        "space-between",
      marginTop: 18,
    },

    galleryFeature: {
      width: "100%",
      height: 210,
      objectFit: "cover",
      backgroundColor:
        "#F2EFE9",
      borderRadius: 7,
      marginBottom: 10,
    },

    galleryHalf: {
      width: "49%",
      height: 128,
      objectFit: "cover",
      backgroundColor:
        "#F2EFE9",
      borderRadius: 7,
      marginBottom: 10,
    },

    galleryWide: {
      width: "100%",
      height: 110,
      objectFit: "cover",
      backgroundColor:
        "#F2EFE9",
      borderRadius: 7,
      marginBottom: 10,
    },

    closingPage: {
      backgroundColor:
        "#17171A",
      color: "#FFFFFF",
      fontFamily:
        "Helvetica",
      paddingTop: 42,
      paddingBottom: 38,
      paddingHorizontal: 42,
    },

    closingBrand: {
      flexDirection: "row",
      alignItems: "center",
    },

    closingLogoBox: {
      width: 52,
      height: 52,
      borderRadius: 10,
      backgroundColor:
        "#FFFFFF",
      padding: 3,
      marginRight: 12,
    },

    closingLogo: {
      width: "100%",
      height: "100%",
      objectFit: "contain",
    },

    closingBrandName: {
      fontSize: 16,
      fontFamily:
        "Helvetica-Bold",
      letterSpacing: 1.2,
      color: "#FFFFFF",
    },

    closingBrandMeta: {
      marginTop: 3,
      fontSize: 6.5,
      letterSpacing: 1.2,
      color: "#77777C",
      textTransform:
        "uppercase",
    },

    closingBody: {
      flex: 1,
      justifyContent:
        "center",
      maxWidth: 500,
    },

    closingEyebrow: {
      fontSize: 7.5,
      fontFamily:
        "Helvetica-Bold",
      letterSpacing: 1.4,
      color: "#D2B36F",
      textTransform:
        "uppercase",
    },

    closingTitle: {
      marginTop: 14,
      maxWidth: 450,
      fontSize: 31,
      lineHeight: 1.08,
      fontFamily:
        "Helvetica-Bold",
      color: "#FFFFFF",
    },

    closingDescription: {
      marginTop: 15,
      maxWidth: 440,
      fontSize: 9.5,
      lineHeight: 1.6,
      color: "#A6A6AA",
    },

    closingAgentCard: {
      marginTop: 28,
      borderWidth: 1,
      borderColor:
        "#343438",
      borderRadius: 15,
      backgroundColor:
        "#202023",
      padding: 20,
    },

    closingAgentRow: {
      flexDirection: "row",
      alignItems: "center",
    },

    closingAgentPhoto: {
      width: 78,
      height: 78,
      borderRadius: 39,
      objectFit: "cover",
      backgroundColor:
        "#343438",
      marginRight: 18,
    },

    closingAgentInitial: {
      width: 78,
      height: 78,
      borderRadius: 39,
      backgroundColor:
        "#343438",
      marginRight: 18,
      alignItems: "center",
      justifyContent:
        "center",
    },

    closingAgentInitialText: {
      fontSize: 26,
      fontFamily:
        "Helvetica-Bold",
      color: "#FFFFFF",
    },

    closingAgentCopy: {
      flex: 1,
    },

    closingAgentName: {
      fontSize: 18,
      fontFamily:
        "Helvetica-Bold",
      color: "#FFFFFF",
    },

    closingAgency: {
      marginTop: 4,
      fontSize: 9,
      color: "#D2B36F",
    },

    closingContactRow: {
      flexDirection: "row",
      marginTop: 16,
    },

    closingContactBox: {
      flex: 1,
      backgroundColor:
        "#111113",
      borderRadius: 7,
      padding: 10,
      marginRight: 7,
    },

    closingContactBoxLast: {
      flex: 1,
      backgroundColor:
        "#111113",
      borderRadius: 7,
      padding: 10,
      marginLeft: 7,
    },

    closingContactLabel: {
      fontSize: 6.5,
      letterSpacing: 0.8,
      color: "#6F6F74",
      textTransform:
        "uppercase",
    },

    closingContactValue: {
      marginTop: 4,
      fontSize: 8.5,
      color: "#E7E7E9",
    },

    closingWebsiteRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 20,
    },

    closingGoldLine: {
      width: 35,
      height: 1,
      backgroundColor:
        "#D2B36F",
      marginRight: 10,
    },

    closingWebsite: {
      fontSize: 9,
      fontFamily:
        "Helvetica-Bold",
      color: "#AFAFB3",
    },

    closingFooter: {
      borderTopWidth: 1,
      borderTopColor:
        "#303034",
      paddingTop: 13,
      fontSize: 7,
      color: "#747479",
    },

    closingPageNumber: {
      position: "absolute",
      bottom: 14,
      right: 20,
      backgroundColor:
        "#29292D",
      color: "#D7D7DA",
      borderRadius: 10,
      paddingHorizontal: 9,
      paddingVertical: 4,
      fontSize: 7,
    },

    agentCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor:
        "#252422",
      borderRadius: 7,
      padding: 11,
      marginTop: 16,
      color: "#FFFFFF",
    },

    agentPhoto: {
      width: 46,
      height: 46,
      borderRadius: 23,
      objectFit: "cover",
      marginRight: 11,
      backgroundColor:
        "#DED8CC",
    },

    agentCopy: {
      flex: 1,
    },

    agentName: {
      fontSize: 11,
      fontFamily:
        "Helvetica-Bold",
      color: "#FFFFFF",
    },

    agentMeta: {
      marginTop: 2,
      fontSize: 7.8,
      color: "#D8D3CB",
    },

    footer: {
      position: "absolute",
      bottom: 15,
      left: 38,
      right: 38,
      flexDirection: "row",
      justifyContent:
        "space-between",
      borderTopWidth: 1,
      borderTopColor:
        "#DED8CC",
      paddingTop: 7,
      fontSize: 7,
      color: "#8A857E",
    },
  });

function valueOrDash(
  value: unknown,
  suffix = ""
) {
  if (
    value === null ||
    value === undefined ||
    value === ""
  ) {
    return "-";
  }

  return `${value}${suffix}`;
}

function detailStats(
  property: PdfProperty,
  language:
    AgentProposalLanguage
) {
  const t =
    dictionary(language);

  return [
    {
      label: t.bedrooms,
      value: valueOrDash(
        property.bedrooms
      ),
    },
    {
      label: t.bathrooms,
      value: valueOrDash(
        property.bathrooms
      ),
    },
    {
      label:
        t.buildingSize,
      value:
        property.buildingSize
          ? `${property.buildingSize} m²`
          : "-",
    },
    {
      label: t.landSize,
      value:
        property.landSize
          ? `${property.landSize} ${property.landUnit || "m²"}`
          : "-",
    },
    {
      label: t.floors,
      value: valueOrDash(
        property.floors
      ),
    },
    {
      label: t.parking,
      value: valueOrDash(
        property.parking
      ),
    },
    {
      label: t.furnishing,
      value: valueOrDash(
        property.furnishing
      ),
    },
    {
      label:
        t.certificate,
      value: valueOrDash(
        property.certificate
      ),
    },
  ];
}

function formatProposalPdfValue(
  value: unknown,
  language: AgentProposalLanguage
) {
  if (
    value === null ||
    value === undefined
  ) {
    return "";
  }

  if (
    typeof value === "number"
  ) {
    return value > 0
      ? String(value)
      : "";
  }

  const raw =
    String(value).trim();

  if (
    !raw ||
    raw === "-" ||
    raw === "0"
  ) {
    return "";
  }

  const key =
    raw
      .toLowerCase()
      .replace(/\s+/g, "_");

  const english:
    Record<string, string> = {
    rumah: "House",
    villa: "Villa",
    apartemen: "Apartment",
    apartment: "Apartment",
    tanah: "Land",
    dijual: "For Sale",
    disewa: "For Rent",
    dijual_disewa:
      "For Sale / Rent",
    tanah_hunian:
      "Residential Land",
    permukiman:
      "Residential",
    fully_furnished:
      "Fully Furnished",
    semi_furnished:
      "Semi Furnished",
    unfurnished:
      "Unfurnished",
  };

  const indonesian:
    Record<string, string> = {
    rumah: "Rumah",
    villa: "Villa",
    apartemen: "Apartemen",
    apartment: "Apartemen",
    tanah: "Tanah",
    dijual: "Dijual",
    disewa: "Disewa",
    dijual_disewa:
      "Dijual / Disewa",
    tanah_hunian:
      "Tanah Hunian",
    permukiman:
      "Permukiman",
    fully_furnished:
      "Fully Furnished",
    semi_furnished:
      "Semi Furnished",
    unfurnished:
      "Tanpa Furnitur",
  };

  const mapped =
    language === "en"
      ? english[key]
      : indonesian[key];

  if (mapped) {
    return mapped;
  }

  return raw
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(
      /\b\w/g,
      (letter) =>
        letter.toUpperCase()
    );
}

function clampProposalPdfText(
  value: string | null | undefined,
  maxLength = 1250
) {
  const clean =
    String(value || "")
      .trim();

  if (
    clean.length <=
    maxLength
  ) {
    return clean;
  }

  return (
    clean.slice(
      0,
      maxLength
    ).trimEnd() +
    "…"
  );
}

function chunkProposalGallery(
  images: string[]
) {
  const galleryImages =
    images.slice(1);

  const chunks:
    string[][] = [];

  for (
    let index = 0;
    index <
    galleryImages.length;
    index += 6
  ) {
    chunks.push(
      galleryImages.slice(
        index,
        index + 6
      )
    );
  }

  return chunks;
}

function PropertyPage({
  property,
  data,
  index,
}: {
  property: PdfProperty;
  data: PdfData;
  index: number;
}) {
  const t =
    dictionary(
      data.language
    );

  const stats = [
    {
      label:
        t.propertyType,
      value:
        formatProposalPdfValue(
          property.propertyType,
          data.language
        ),
    },
    {
      label:
        t.listingType,
      value:
        formatProposalPdfValue(
          property.listingType,
          data.language
        ),
    },
    ...detailStats(
      property,
      data.language
    ).map(
      (item) => ({
        ...item,
        value:
          formatProposalPdfValue(
            item.value,
            data.language
          ),
      })
    ),
  ].filter(
    (item) =>
      Boolean(
        item.value
      )
  );

  const detailRows = [
    [
      t.furnishing,
      property.furnishing,
    ],
    [
      t.certificate,
      property.certificate,
    ],
    [
      t.roadAccess,
      property.roadAccess,
    ],
    [
      t.ownership,
      property.ownershipType,
    ],
    [
      t.landType,
      property.landType,
    ],
    [
      t.zoning,
      property.zoningType,
    ],
    [
      t.water,
      property.water,
    ],
  ]
    .map(
      ([
        label,
        value,
      ]) => [
        label,
        formatProposalPdfValue(
          value,
          data.language
        ),
      ]
    )
    .filter(
      ([, value]) =>
        Boolean(value)
    );

  return (
    <Page
      size="A4"
      style={styles.page}
    >
      <View
        style={styles.header}
      >
        <View
          style={
            styles.headerBrand
          }
        >
          <Image
            src={
              data.brandLogoDataUrl
            }
            style={
              styles.headerLogo
            }
          />

          <View>
            <Text
              style={
                styles.headerBrandText
              }
            >
              TETAMO
            </Text>

            <Text
              style={
                styles.listingCode
              }
            >
              {t.listingCode}:{" "}
              {property.kode ||
                "-"}
            </Text>
          </View>
        </View>

        <Text
          style={
            styles.listingCode
          }
        >
          {index + 1} /{" "}
          {data.properties.length}
        </Text>
      </View>

      <Text
        style={
          styles.propertyKicker
        }
      >
        {data.language === "id"
          ? `Properti ${index + 1}`
          : `Property ${index + 1}`}
      </Text>

      <Text
        style={
          styles.propertyTitle
        }
      >
        {property.title}
      </Text>

      <Text
        style={
          styles.location
        }
      >
        {property.location ||
          property.address ||
          "-"}
      </Text>

      <Text
        style={styles.price}
      >
        {property.priceText}
      </Text>

      <View
        style={
          styles.statGrid
        }
      >
        {stats
          .slice(0, 8)
          .map((item) => (
            <View
              key={
                item.label
              }
              style={
                styles.stat
              }
            >
              <View
                style={
                  styles.statInner
                }
              >
                <Text
                  style={
                    styles.statLabel
                  }
                >
                  {item.label}
                </Text>

                <Text
                  style={
                    styles.statValue
                  }
                >
                  {item.value}
                </Text>
              </View>
            </View>
          ))}
      </View>

      <View
        style={
          styles.twoColumn
        }
      >
        <View
          style={
            styles.mainColumn
          }
        >
          <Text
            style={
              styles.sectionTitle
            }
          >
            {t.description}
          </Text>

          <Text
            style={styles.body}
          >
            {clampProposalPdfText(
              property.description
            ) || "-"}
          </Text>

          {property.facilities
            .length > 0 ? (
            <View
              style={{
                marginTop: 13,
              }}
            >
              <Text
                style={
                  styles.sectionTitle
                }
              >
                {t.facilities}
              </Text>

              {property.facilities
                .slice(0, 10)
                .map(
                  (facility) => (
                    <Text
                      key={
                        facility
                      }
                      style={
                        styles.bullet
                      }
                    >
                      •{" "}
                      {formatProposalPdfValue(
                        facility,
                        data.language
                      )}
                    </Text>
                  )
                )}
            </View>
          ) : null}
        </View>

        <View
          style={
            styles.sideColumn
          }
        >
          {detailRows.length >
          0 ? (
            <View
              style={
                styles.infoBox
              }
            >
              <Text
                style={
                  styles.sectionTitle
                }
              >
                {t.propertyDetails}
              </Text>

              {detailRows.map(
                ([
                  label,
                  value,
                ]) => (
                  <Text
                    key={
                      label
                    }
                    style={
                      styles.bullet
                    }
                  >
                    {label}:{" "}
                    {value}
                  </Text>
                )
              )}
            </View>
          ) : null}

          {property.nearby
            .length > 0 ? (
            <View
              style={
                styles.infoBox
              }
            >
              <Text
                style={
                  styles.sectionTitle
                }
              >
                {t.nearby}
              </Text>

              {property.nearby
                .slice(0, 6)
                .map(
                  (item) => (
                    <Text
                      key={
                        item
                      }
                      style={
                        styles.bullet
                      }
                    >
                      •{" "}
                      {formatProposalPdfValue(
                        item,
                        data.language
                      )}
                    </Text>
                  )
                )}
            </View>
          ) : null}

          <View
            style={
              styles.infoBox
            }
          >
            <View
              style={
                styles.qrRow
              }
            >
              <Image
                src={
                  property.qrDataUrl
                }
                style={
                  styles.qr
                }
              />

              <View
                style={
                  styles.qrCopy
                }
              >
                <Text
                  style={
                    styles.qrTitle
                  }
                >
                  {t.viewOnline}
                </Text>

                <Text
                  style={
                    styles.qrText
                  }
                >
                  {t.scanQr}
                </Text>
              </View>
            </View>
          </View>
        </View>
      </View>

      <View
        style={styles.footer}
        fixed
      >
        <Text>
          {t.generatedBy}
        </Text>

        <Text
          render={({
            pageNumber,
          }) =>
            `${t.page} ${pageNumber}`
          }
        />
      </View>
    </Page>
  );
}

function GalleryPage({
  property,
  data,
  propertyIndex,
  images,
  galleryPageIndex,
}: {
  property: PdfProperty;
  data: PdfData;
  propertyIndex: number;
  images: string[];
  galleryPageIndex: number;
}) {
  const t =
    dictionary(
      data.language
    );

  const firstPhotoNumber =
    2 +
    galleryPageIndex *
      6;

  const lastPhotoNumber =
    firstPhotoNumber +
    images.length -
    1;

  return (
    <Page
      size="A4"
      style={
        styles.galleryPage
      }
    >
      <View
        style={
          styles.galleryHeader
        }
      >
        <View>
          <Text
            style={
              styles.galleryEyebrow
            }
          >
            {data.language === "id"
              ? `Properti ${propertyIndex + 1} • Galeri`
              : `Property ${propertyIndex + 1} • Gallery`}
          </Text>

          <Text
            style={
              styles.galleryTitle
            }
          >
            {t.gallery}
          </Text>

          <Text
            style={
              styles.galleryPropertyTitle
            }
          >
            {property.title}
          </Text>
        </View>

        <View>
          <Text
            style={
              styles.galleryPhotoLabel
            }
          >
            {t.photos}
          </Text>

          <Text
            style={
              styles.galleryPhotoRange
            }
          >
            {firstPhotoNumber}
            {" – "}
            {lastPhotoNumber}
          </Text>
        </View>
      </View>

      <View
        style={
          styles.galleryGrid
        }
      >
        {images.map(
          (
            image,
            imageIndex
          ) => {
            const isFeature =
              imageIndex === 0;

            const isLast =
              imageIndex ===
              images.length - 1;

            const shouldSpanLast =
              !isFeature &&
              isLast &&
              images.length % 2 ===
                0;

            return (
              <Image
                key={`${property.id}-${galleryPageIndex}-${imageIndex}`}
                src={image}
                style={
                  isFeature
                    ? styles.galleryFeature
                    : shouldSpanLast
                      ? styles.galleryWide
                      : styles.galleryHalf
                }
              />
            );
          }
        )}
      </View>

      <View
        style={styles.footer}
        fixed
      >
        <Text>
          TETAMO • Properti Marketplace
        </Text>

        <Text
          render={({
            pageNumber,
          }) =>
            `${t.page} ${pageNumber}`
          }
        />
      </View>
    </Page>
  );
}

function ClosingPage({
  data,
}: {
  data: PdfData;
}) {
  const t =
    dictionary(
      data.language
    );

  const initial =
    (
      data.agent.fullName ||
      "T"
    )
      .charAt(0)
      .toUpperCase();

  return (
    <Page
      size="A4"
      style={
        styles.closingPage
      }
    >
      <View
        style={
          styles.closingBrand
        }
      >
        <View
          style={
            styles.closingLogoBox
          }
        >
          <Image
            src={
              data.brandLogoDataUrl
            }
            style={
              styles.closingLogo
            }
          />
        </View>

        <View>
          <Text
            style={
              styles.closingBrandName
            }
          >
            TETAMO
          </Text>

          <Text
            style={
              styles.closingBrandMeta
            }
          >
            Properti • Marketplace
          </Text>
        </View>
      </View>

      <View
        style={
          styles.closingBody
        }
      >
        <Text
          style={
            styles.closingEyebrow
          }
        >
          {t.contactAgent}
        </Text>

        <Text
          style={
            styles.closingTitle
          }
        >
          {t.interestedTitle}
        </Text>

        <Text
          style={
            styles.closingDescription
          }
        >
          {t.interestedBody}
        </Text>

        <View
          style={
            styles.closingAgentCard
          }
        >
          <View
            style={
              styles.closingAgentRow
            }
          >
            {data.agent.photoUrl ? (
              <Image
                src={
                  data.agent.photoUrl
                }
                style={
                  styles.closingAgentPhoto
                }
              />
            ) : (
              <View
                style={
                  styles.closingAgentInitial
                }
              >
                <Text
                  style={
                    styles.closingAgentInitialText
                  }
                >
                  {initial}
                </Text>
              </View>
            )}

            <View
              style={
                styles.closingAgentCopy
              }
            >
              <Text
                style={
                  styles.closingAgentName
                }
              >
                {data.agent.fullName ||
                  "Tetamo Agent"}
              </Text>

              {data.agent.agency ? (
                <Text
                  style={
                    styles.closingAgency
                  }
                >
                  {data.agent.agency}
                </Text>
              ) : null}
            </View>
          </View>

          {data.agent.phone ||
          data.agent.email ? (
            <View
              style={
                styles.closingContactRow
              }
            >
              {data.agent.phone ? (
                <View
                  style={
                    styles.closingContactBox
                  }
                >
                  <Text
                    style={
                      styles.closingContactLabel
                    }
                  >
                    {t.phoneWhatsApp}
                  </Text>

                  <Text
                    style={
                      styles.closingContactValue
                    }
                  >
                    {data.agent.phone}
                  </Text>
                </View>
              ) : null}

              {data.agent.email ? (
                <View
                  style={
                    data.agent.phone
                      ? styles.closingContactBoxLast
                      : styles.closingContactBox
                  }
                >
                  <Text
                    style={
                      styles.closingContactLabel
                    }
                  >
                    Email
                  </Text>

                  <Text
                    style={
                      styles.closingContactValue
                    }
                  >
                    {data.agent.email}
                  </Text>
                </View>
              ) : null}
            </View>
          ) : null}
        </View>

        <View
          style={
            styles.closingWebsiteRow
          }
        >
          <View
            style={
              styles.closingGoldLine
            }
          />

          <Text
            style={
              styles.closingWebsite
            }
          >
            tetamo.com
          </Text>
        </View>
      </View>

      <View
        style={
          styles.closingFooter
        }
      >
        <Text>
          {t.generatedBy}
        </Text>
      </View>

      <Text
        style={
          styles.closingPageNumber
        }
        render={({
          pageNumber,
        }) =>
          `${t.page} ${pageNumber}`
        }
      />
    </Page>
  );
}

function AgentProposalDocument({
  data,
}: {
  data: PdfData;
}) {
  const t =
    dictionary(
      data.language
    );

  const coverImage =
    data.properties[0]
      ?.images[0] || "";

  const isPortfolio =
    data.mode ===
      "portfolio" ||
    data.properties.length > 1;

  return (
    <Document>
      <Page
        size="A4"
        style={
          styles.coverPage
        }
      >
        <View
          style={
            styles.coverTop
          }
        >
          <Image
            src={
              data.brandLogoDataUrl
            }
            style={
              styles.logo
            }
          />

          <Text
            style={
              styles.eyebrow
            }
          >
            TETAMO
          </Text>

          <Text
            style={
              styles.coverTitle
            }
          >
            {isPortfolio
              ? t.propertyPortfolio
              : t.propertyProposal}
          </Text>

          {data.buyerName ? (
            <>
              <Text
                style={
                  styles.buyerLabel
                }
              >
                {t.preparedFor}
              </Text>

              <Text
                style={
                  styles.buyerName
                }
              >
                {data.buyerName}
              </Text>

              {data.buyerCompany ? (
                <Text
                  style={
                    styles.buyerCompany
                  }
                >
                  {data.buyerCompany}
                </Text>
              ) : null}
            </>
          ) : null}

          {data.introduction ? (
            <Text
              style={
                styles.intro
              }
            >
              {data.introduction}
            </Text>
          ) : null}
        </View>

        {coverImage ? (
          <Image
            src={coverImage}
            style={
              styles.coverHero
            }
          />
        ) : (
          <View
            style={
              styles.coverHero
            }
          />
        )}

        <View
          style={
            styles.coverBottom
          }
        >
          <View>
            <Text
              style={
                styles.buyerLabel
              }
            >
              {t.preparedBy}
            </Text>

            <Text
              style={
                styles.coverAgentName
              }
            >
              {data.agent.fullName ||
                "Tetamo Agent"}
            </Text>

            <Text
              style={
                styles.coverAgentMeta
              }
            >
              {data.agent.agency ||
                "Tetamo Partner"}
            </Text>
          </View>

          <Text
            style={
              styles.propertyCount
            }
          >
            {t.selectedProperties}:{" "}
            {data.properties.length}
          </Text>
        </View>

        <Text
          style={
            styles.coverPageNumber
          }
        >
          {t.page} 1
        </Text>
      </Page>

      {data.properties.map(
        (
          property,
          index
        ) => {
          const galleryPages =
            chunkProposalGallery(
              property.images
            );

          return [
            <PropertyPage
              key={`${property.id}-details`}
              property={
                property
              }
              data={data}
              index={index}
            />,
            ...galleryPages.map(
              (
                images,
                galleryPageIndex
              ) => (
                <GalleryPage
                  key={`${property.id}-gallery-${galleryPageIndex}`}
                  property={
                    property
                  }
                  data={data}
                  propertyIndex={
                    index
                  }
                  images={
                    images
                  }
                  galleryPageIndex={
                    galleryPageIndex
                  }
                />
              )
            ),
          ];
        }
      )}

      <ClosingPage
        data={data}
      />
    </Document>
  );
}

export async function generateAgentProposalPdf(
  input: AgentProposalData
) {
  const [
    properties,
    logoBuffer,
  ] =
    await Promise.all([
      Promise.all(
        input.properties.map(
          async (property) => ({
            ...property,
            qrDataUrl:
              await QRCode.toDataURL(
                property.publicUrl,
                {
                  width: 260,
                  margin: 1,
                  errorCorrectionLevel:
                    "M",
                }
              ),
          })
        )
      ),
      readFile(
        path.join(
          process.cwd(),
          "public",
          "tetamo-logo-transparent1.png"
        )
      ),
    ]);

  const brandLogoDataUrl =
    `data:image/png;base64,${logoBuffer.toString("base64")}`;

  const data: PdfData = {
    ...input,
    properties,
    brandLogoDataUrl,
  };

  return renderToBuffer(
    <AgentProposalDocument
      data={data}
    />
  );
}
